### ISSUE TITLE
Metrics/AbcSizeを15から17に緩めたい

### ISSUE THREAD

**Issue by lastgleam** [Fablic/fablicop#28]
# 対象規約
`Metrics/AbcSize`

## 種類
修正

### 制限が厳しい
個人的にたった条件式1~2行追加で怒られて（特にFeatureToggle仕込む時）
リファクタリングしないといけないことになってしまうケースが何回かあった。

### `# rubocop: disable Metrics/AbcSize`が多い
IDEを使っていなくてrubocopを手動で回している場合、実装終えてからAbcSizeを指摘されると
書いたコードを全体的に見直さないといけなくなり修正に負担がかかってしまう。
その修正を諦めて`Metrics/AbcSize`をdisableしてしまうのも多々ある。
なるべくdisableするのを減らしたいし。

## 備考
ちょうど`rubocop`本体もMetrics/AbcSizeを17にするPRがmasterブランチにマージされた。
https://github.com/rubocop-hq/rubocop/pull/8037

**Comment by ujihisa** [comment]
![image](https://user-images.githubusercontent.com/11504/92542199-04eecc00-f1fd-11ea-8152-88620ef92cea.png)

**Comment by ujihisa** [comment]
s/FeatureToggle/FeatureToggles/
