### ISSUE TITLE
Transfer the owners

### ISSUE THREAD

**Issue by ujihisa** [Fablic/fablicop#32]
https://rubygems.org/gems/fablicop
そろそろオーナーのうちFablic退職者を消していって、現ラクマ開発の人をメインにするのがよさそう

**Comment by lastgleam** [comment]
@ysk1180 を推薦します

**Comment by ujihisa** [comment]
今確認したところ @ysk1180 さんすでにオーナーなので、現職の他の人の追加もがんがんできそうです :+1:

![image](https://user-images.githubusercontent.com/11504/103025112-fb684600-4505-11eb-85e5-46d6b35fef92.png)

(あと本件とまったく関係ないけど、 @ShoheiMitani @sinamon129 @kazu9su さんはrubygems.orgのMFA有効にしてください! Fablicopとは関係なく、一般のアカウント乗っ取り対策です)

**Comment by ysk1180** [comment]
めっちゃ遅くなってすみません 🙇 

@lastgleam さんと、@Kazumpo さんを追加しました！ 🎉 

![image](https://user-images.githubusercontent.com/34002043/105673084-db72da80-5f28-11eb-9360-5f1d80ae849d.png)

**Comment by ujihisa** [comment]
:banjaku::goodpoem:

**Comment by kazu9su** [comment]
うじさんどうやってgithub nitificationチェックしてるんだ…(MFA有効にしました)

**Comment by ujihisa** [comment]
普通にemailみてます...!
