### ISSUE TITLE
Disable to RSpec/LetSetup

### ISSUE THREAD

**Issue by sourcewc** [Fablic/fablicop#62]
I have a suggestion.
fablicop is warning to let! but so many rspec cases using the let!
it is so complexity problem when i create spec for refectoring or add to existing functions.
may i suggest disable RSpec/LetSetup.

**Comment by yykamei** [comment]
That's understandable that it's difficult to follow the cop [RSpec/LetSetup](https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecletsetup) with an old application. However, I think RSpec/LetSetup is useful when creating new tests. As you know, `let` evaluates the block in a *lazy* way, so this won't be loaded on examples that don't use the expression. This might avoid unnecessary loading and make tests a bit faster.

**Comment by sourcewc** [comment]
Thank you for response my issue.
I understand RSpec/LetSetup is good to perfomance issue for rspec.
recently, i used `rubocop:disable RSpec/LetSetup` for add case in existing function because ci warning and code review.
it's inefficiency when we add to spec.
so if we can ci warning surpress only RSpec/LetSetup, that looks so good
