### ISSUE TITLE
Disable RSpec/NamedSubject

### ISSUE THREAD

**Issue by tana2034** [Fablic/fablicop#68]
https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecnamedsubject

for `RSpec/NamedSubject`,a good example from the official documentation is as follows:

```Ruby
# good
RSpec.describe Foo do
  subject(:user) { described_class.new }

  it 'is valid' do
    expect(user.valid?).to be(true)
  end
end
```

So I think NamedSubject is basically used in the model class specs.
However, NamedSubject applies to controller specs and request specs. I would like to remove it because it names the subject with a name that is not a class name, which does not make sense at first glance when reading it.

```Ruby
subject (:request_to_api) { get '/api/users' }

it 'returns 200' do
  request_to_api # <- what is it?
  expect(response).to have_http_status(200)
end
```

**Comment by yykamei** [comment]
In the first place, I don't like the method `subject` because it's difficult for me to read the test codes: what is subject 🤷

**Comment by tana2034** [comment]
If `subject` is not used, this problem does not occur.
If someone uses `subject`, this problem occurs, and as long as the use of `subject` is not prohibited, I hope you will consider disable of this rule.

(By the way, I don't dislike `subject` so much because I consider it as a subject to explain the specification. Rather, I find it easier to understand if it is always `subject`)

**Comment by yykamei** [comment]
`subject` tends to depend on many identifiers declared with `let` or `let!` like this.

```ruby
subject { get '/foo', params: { foo_id: foo_id, bar: bar } }

context 'when A' do
  let(:foo_id) { 123 }
  let(:bar) { '😇' }

  it { is_expected.to eq 200 }
end

context 'when B' do
  let(:foo_id) { 123 }
  let(:bar) { '😎' }

  it { is_expected.to eq 302 }
end

# ... many contexts appear!
```

When I read this code, I have to move my eyes upward to find what `subject` is, and I must get back to examples to what are `foo_id` and `bar`. Using `subject` is likely to cause distribute many identifiers throughout the test file, so it causes the tests difficult to read.

So, I want to prohibit using the `subject` itself (I know it might be a bit radical...)

**Comment by tana2034** [comment]
> When I read this code, I have to move my eyes upward to find what subject is, and I must get back to examples to what are foo_id and bar.

yeah agree, so I mean **when using `subject`**, normal `subject` is easier for me to understand than `namedSubject`. Also, since I am not considering banning using `subject`, I would like to make NamedSubject disable!

**Comment by taheryasir** [comment]
> subject (:request_to_api) { get '/api/users' }
> 
> it 'returns 200' do
>   request_to_api # <- what is it?
>   expect(response).to have_http_status(200)
> end

for me above one is more understandable to me. for example when I see the subject request_to_api i understand that it is requesting to an API but if i use it just subject i will have to check what subject is supposed to do.

**Comment by tana2034** [comment]
I doubt it... 🤔  people give different names to `subject` and I find it difficult to tell if it is a `subject` or not.

On the other hand, when normal `subject` is used, I understand `subject` as the subject of the test (I don't know how do I express this...)
And I think the scope specified by `describe` should be the `subject`.
So, in the following case, the subject would be `User`:

```Ruby
describe User do
    ...
   it 'returns true' do
       expect(subject.valid?).to eq true  # I haven't seen subject but it should be User instance 🤔 
   end
end
```

In the following case, the subject would be `User.valid?`

```Ruby
describe User do
    describe '#valid?' do
    ...
        it 'returns true' do
            expect(subject).to eq true  # I haven't seen subject but it should be user.valid? 🤔 
        end
    end
end

```

and I understand request spec as follows:

```Ruby

describe 'Users' do
    describe 'get /users' do
    ...
        it 'returns 200' do
            subject   # I haven't seen subject but it should be `get /users` 🤔 
            expect(response).to have_http_status(200)
        end
    end
end
```

**Comment by yykamei** [comment]
OK, I understood. Let's disable `RSpec/NamedSubject`. Thanks, @tana2034
