### ISSUE TITLE
Change RSpec/ExampleLength MAX value from 5 -> 7

### ISSUE THREAD

**Issue by tana2034** [Fablic/fablicop#69]
https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecexamplelength
It feels too short.
Short EXAMPLES are easy to look at, but often do not cover the large number of DB settings.
and It is not possible to define many `let` because of `RSpec/MultipleMemoizedHelpers`.
However, in my opinion, I would rather have more lines of example than more `let`, because I think there is less information to look at when the example fails.

**Comment by yykamei** [comment]
I agree!

I think we can completely disable the cop itself!

**Comment by taheryasir** [comment]
> I think we can completely disable the cop itself!

**Comment by taheryasir** [comment]
>I think we can completely disable the cop itself!

you mean disable `RSpec/MultipleMemoizedHelpers` ?

**Comment by yykamei** [comment]
No, `RSpec/ExampleLength` should be disabled.

**Comment by taheryasir** [comment]
i would suggest to disable `RSpec/MultipleMemoizedHelpers` too

**Comment by yykamei** [comment]
The default value of `RSpec/MultipleMemoizedHelpers` is a bit strict, but I think this cop is helpful for me because it alerts the excessive use of `let`.

**Comment by taheryasir** [comment]
That is true, but it seems no one cares about this as there are lot of `MultipleMemoizedHelpers` errors

**Comment by tana2034** [comment]
@yykamei 
Would it be better to disable it than to increase the maximum? 👀 
In fact, since we have [`RSpec/MultipleExpectations`](https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecmultipleexpectations), I am thinking that disabling `RSpec/ExampleLength` will not make the examples much longer.

**Comment by yykamei** [comment]
Yes, we should disable this. For example, I wrote a test like this:

```ruby
it do
  expect(response).to be_json(
    user: {
      id: 123,
      name: 'foo',
      display_name: 'Foo',
    },
    something: true,
    a: false,
    b: true,
    c: true,
  )
end
```

In this case, `RSpec/ExampleLength` is annoying for me.

Note the above case should expect the whole response body, so splitting it into multiple tests does not make sense. I expect the test fails when I add a new field.

Bad:

```ruby
it do
  expect(data[:user][:id]).to eq 123
end

it do
  expect(data[:user][:name]).to eq 'Foo'
end

# Even if I added a new field to `:user`, theses tests won't fail. It's bad for me
```
